# ==========================================
# CONFIGURACIÓN DEL SERVIDOR
# ==========================================
server.port=8085
spring.application.name=ms-direcciones

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/ferrefixadress
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Ruta del Script para liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog.sql
spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# CONFIGURACIÓN DE LOGS (SLF4J)
# ==========================================
# Ruta y nombre del archivo de logs
logging.file.name=ms_direcciones/logs/direcciones-service.log

# Formato del log en archivo (con fecha, hilo, nivel, clase y mensaje)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
# Formato del log en consola (con colores)
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%thread]){faint} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n
