server:
  port: 8080 # Puerto estándar de interacción

spring:
  main:
    web-application-type: reactive # Obliga a correr en un servidor Netty

  security:
    oauth2:
      resourceserver:
        jwt:
        # Clave secreta para la autenticacion de los tokens
          secret-key: "clavesupersecreta"

  cloud:
    gateway:
      routes:
      # URI (Identificador Universal de Recursos)
        - id: ms-usuarios
          uri: lb://ms-usuarios
          predicates:
            - Path=/api/usuarios/**

        - id: ms-inventario
          uri: lb://ms-inventario
          predicates:
            - Path=/api/inventario/**

        - id: ms-ventas
          uri: lb://ms-ventas
          predicates:
            - Path=/api/ventas/**

        - id: ms-proveedores
          uri: lb://ms-proveedores
          predicates:
            - Path=/api/proveedores/**

        - id: ms-direcciones
          uri: lb://ms-direcciones
          predicates:
            - Path=/api/direcciones/**
    
    # Rutas en Construcción (probablemente se queden igual)
        - id: ms-marcas
          uri: lb://ms-marcas
          predicates:
            - Path=/api/marcas/**

        - id: ms-herramientas-arriendo
          uri: lb://ms-herramientas-arriendo
          predicates:
            - Path=/api/arriendos/**

        - id: ms-compras
          uri: lb://ms-compras
          predicates:
            - Path=/api/compras/**

        - id: ms-reportes
          uri: lb://ms-reportes
          predicates:
            - Path=/api/reportes/**

        - id: ms-notificaciones
          uri: lb://ms-notificaciones
          predicates:
            - Path=/api/notificaciones/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/