spring.application.name=ms_marcas
server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3306/ferrefixmarcas
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

logging.file.name=ms_marcas/logs/marcas.log
logging.pattern.console=%d{HH:mm:ss} %-5level %msg%n
logging.pattern.file=%d{HH:mm:ss} %-5level %msg%n
