spring.application.name=ms_usuarios
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/ferrefixusr
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# ============ CONFIGURACIÓN DE LOGGING ============
# Archivo de log
logging.file.name=ms_usuarios/logs/usuarios.log

# Formato de log en consola
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Formato de log en archivo
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Rutas para la comunicación con otros microservicios a través del API Gateway (Puede que este apuntando mal)
api.gateway.url=http://ms-gateway:8080
api.usuarios.path=/api/direcciones
