spring.application.name=ms_inventario
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/ferrefixinv
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
# Lo dejo documentado por mientas jeje
spring.jpa.show-sql=false

# Archivos que permaneceran en el ms_inventario para el funcionamiento de loggin
logging.file.name=ms_inventario/logs/inventario-service.log
logging.pattern.console=%d{HH:mm:ss} %-5level %msg%n
logging.pattern.file=%d{HH:mm:ss} %-5level %msg%n