server:
  port: 8080 # Puerto estándar de interacción

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha

spring:
  main:
    web-application-type: reactive # Obliga a correr en un servidor Netty

  security:
    oauth2:
      resourceserver:
        jwt:
        # Clave secreta para la autenticacion de los tokens (minimo 32 caracteres para HS256)
          secret-key: "FerreFix_Secure_JWT_Secret_Key_2024_!@#"

  cloud:
    gateway:
      routes:
        # URI (Identificador Universal de Recursos)
        - id: ms-auth
          uri: http://localhost:8092
          predicates:
            - Path=/auth/**

        - id: ms-usuarios
          uri: http://localhost:8082
          predicates:
            - Path=/api/usuarios/**

        - id: ms-inventario
          uri: http://localhost:8081
          predicates:
            - Path=/api/inventario/**

        - id: ms-ventas
          uri: http://localhost:8083
          predicates:
            - Path=/api/ventas/**

        - id: ms-proveedores
          uri: http://localhost:8084
          predicates:
            - Path=/api/proveedores/**

        - id: ms-direcciones
          uri: http://localhost:8085
          predicates:
            - Path=/api/direcciones/**
    
        - id: ms-marcas
          uri: http://localhost:8086
          predicates:
            - Path=/api/marcas/**

        - id: ms-arriendo
          uri: http://localhost:8087
          predicates:
            - Path=/api/arriendos/**

        - id: ms-compras
          uri: http://localhost:8088
          predicates:
            - Path=/api/compras/**

        - id: ms-sugerencia
          uri: http://localhost:8089
          predicates:
            - Path=/api/sugerencias/**

        - id: ms-reportes
          uri: http://localhost:8090
          predicates:
            - Path=/api/reportes/**
