spring.application.name=ms_ventas

server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3310/ferrefixventas 
spring.datasource.username=root
spring.datasource.password=iha3gaFBMMzwiee8

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true