# ============================================================
# EUREKA SERVER - Puerto 8761
# ============================================================
# Acá corremos el servidor de descubrimiento. Todos los
# microservicios van a registrarse aquí.

server.port=8761
spring.application.name=eureka-server

# ============================================================
# CONFIGURACIÓN DE EUREKA COMO SERVIDOR
# ============================================================
# Le decimos explícitamente que este es el servidor Eureka
eureka.server.enable-self-preservation=false

# No nos auto-registramos. Este proceso es el servidor,
# no un cliente que se busca a sí mismo.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ============================================================
# CONFIGURACIÓN DEL DASHBOARD
# ============================================================
# El dashboard de Eureka estará disponible en http://localhost:8761
# desde ahí verás todos los microservicios registrados en tiempo real

eureka.server.wait-time-in-ms-when-sync-empty=5
eureka.instance.hostname=eureka-server
